onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /TB_SPE/dut/spu/pc_reg/clk
add wave -noupdate /TB_SPE/dut/spu/pc_reg/rst
add wave -noupdate /TB_SPE/dut/spu/pc_reg/pc
add wave -noupdate /TB_SPE/dut/spu/if_id/if_inst
add wave -noupdate /TB_SPE/dut/spu/id/id_pc
add wave -noupdate /TB_SPE/dut/spu/id/inst_l
add wave -noupdate /TB_SPE/dut/spu/id/inst_h
add wave -noupdate /TB_SPE/dut/spu/id/op_code_e
add wave -noupdate /TB_SPE/dut/spu/id/ra_do_e
add wave -noupdate /TB_SPE/dut/spu/id/rb_do_e
add wave -noupdate /TB_SPE/dut/spu/id/rt_addr_e
add wave -noupdate /TB_SPE/dut/spu/id/wreg_e
add wave -noupdate /TB_SPE/dut/spu/id/op_code_o
add wave -noupdate /TB_SPE/dut/spu/id/ra_do_o
add wave -noupdate /TB_SPE/dut/spu/id/rb_do_o
add wave -noupdate /TB_SPE/dut/spu/id/rt_addr_o
add wave -noupdate /TB_SPE/dut/spu/id/wreg_o
add wave -noupdate /TB_SPE/dut/spu/ex_even/o_rt_e
add wave -noupdate /TB_SPE/dut/spu/ex_even/o_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ex_even/o_wreg_e
add wave -noupdate /TB_SPE/dut/spu/ex_even/o_uid_e
add wave -noupdate /TB_SPE/dut/spu/ex_odd/o_rt_o
add wave -noupdate /TB_SPE/dut/spu/ex_odd/o_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ex_odd/o_wreg_o
add wave -noupdate /TB_SPE/dut/spu/ex_odd/o_uid_o
add wave -noupdate /TB_SPE/dut/spu/ex_ff/ex_rt_e
add wave -noupdate /TB_SPE/dut/spu/ex_ff/ex_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ex_ff/ex_rt_o
add wave -noupdate /TB_SPE/dut/spu/ex_ff/ex_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ff1/ff1_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ff1/ff1_rt_e
add wave -noupdate /TB_SPE/dut/spu/ff1/ff1_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ff1/ff1_rt_o
add wave -noupdate /TB_SPE/dut/spu/ff2/ff2_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ff2/ff2_rt_e
add wave -noupdate /TB_SPE/dut/spu/ff2/ff2_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ff2/ff2_rt_o
add wave -noupdate /TB_SPE/dut/spu/ff3/ff3_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ff3/ff3_rt_e
add wave -noupdate /TB_SPE/dut/spu/ff3/ff3_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ff3/ff3_rt_o
add wave -noupdate /TB_SPE/dut/spu/ff4/ff4_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ff4/ff4_rt_e
add wave -noupdate /TB_SPE/dut/spu/ff4/ff4_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ff4/ff4_rt_o
add wave -noupdate /TB_SPE/dut/spu/ff5/ff5_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ff5/ff5_rt_e
add wave -noupdate /TB_SPE/dut/spu/ff5/ff5_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ff5/ff5_rt_o
add wave -noupdate /TB_SPE/dut/spu/ff6/ff6_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ff6/ff6_rt_e
add wave -noupdate /TB_SPE/dut/spu/ff6/ff6_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ff6/ff6_rt_o
add wave -noupdate /TB_SPE/dut/spu/ff7/ff7_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ff7/ff7_rt_e
add wave -noupdate /TB_SPE/dut/spu/ff7/ff7_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ff7/ff7_rt_o
add wave -noupdate /TB_SPE/dut/spu/ff_mem/mem_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/ff_mem/mem_rt_e
add wave -noupdate /TB_SPE/dut/spu/ff_mem/mem_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/ff_mem/mem_rt_o
add wave -noupdate /TB_SPE/dut/spu/mem/o_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/mem/o_rt_e
add wave -noupdate /TB_SPE/dut/spu/mem/o_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/mem/o_rt_o
add wave -noupdate /TB_SPE/dut/spu/mem_wb/wb_rtaddr_e
add wave -noupdate /TB_SPE/dut/spu/mem_wb/wb_rt_e
add wave -noupdate /TB_SPE/dut/spu/mem_wb/wb_rtaddr_o
add wave -noupdate /TB_SPE/dut/spu/mem_wb/wb_rt_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {217207 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 229
configure wave -valuecolwidth 225
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {208770 ps} {487141 ps}
